### ISSUE TITLE
Set up new repository for Alliance API (internal api between analytics server and oracle)

### ISSUE THREAD

**Issue by geneorama** [Chicago/lead-public#15]
@tomschenkjr @potash is has started a new repo for the Alliance API development.  Currently it's a private dssg repo, but we should transfer it to Chicago.

**Comment by geneorama** [comment]
The transfer failed... unable to create repository in target account.  So can we create a new repository under Chicago?

**Comment by geneorama** [comment]
@tomschenkjr Another idea, maybe we should do it on the internal gitlab?  If we can grant @potash and @avishekrk usernames, they'll be able to access within the VPN.

**Comment by tomschenkjr** [comment]
Yes, Alliance API being developed by Sun is on GitLab.

Internal code should also be on GitLab.

We can strive for the lead model to be on GitHub so it can be replicated by others.

**Comment by geneorama** [comment]
Ok, so we can set up @avishekrk when his COC credentials are complete, and then add Eric / set up the repository then also.   

For the time being, they're creating the code on our server, so hopefully we can keep it there and keep making commits locally, but just refrain from pushing them to the ultimate repo.

**Comment by geneorama** [comment]
Also, I updated the issue name to be more specific about the API (i.e. this isn't the external API that Sun is developing).

**Comment by avishekrk** [comment]
@geneorama can this issue be closed now?

**Comment by geneorama** [comment]
Yes, thanks.
