### ISSUE TITLE
Split into separate ETL and model repos

### ISSUE THREAD

**Issue by potash** [Chicago/lead-public#16]
The project will be easier to maintain and port to new data sources after splitting into separate ETL (extract, transform, load) and modeling repositories. I have started this process in my personal github: [lead-etl](https://github.com/potash/lead-etl) and [lead-model](https://github.com/potash/lead-model)

**Comment by potash** [comment]
Okay the above linked repositories are ready to go and have updated documentation, just tested a full build on analytics.

@geneorama can you fork them into the `chicago` organization? when you're done, i will close this issue and copy the remaining issues out, and then this repo (`lead-public`) can be deleted.

**Comment by geneorama** [comment]
Great, thanks they're forked over into Chicago.

**Comment by potash** [comment]
Can you give me write access to them so I can create issues, PRs etc?

**Comment by geneorama** [comment]
Just added you

**Comment by potash** [comment]
Oh, you need to [manually enable issues on a fork](https://stackoverflow.com/questions/16406180/is-there-a-way-to-add-issues-to-a-github-forked-repo-without-modifying-the-orig), assuming we want the issues to live there instead of on `potash/lead-model`.

**Comment by geneorama** [comment]
Good call, issues are enabled (now they are).

**Comment by geneorama** [comment]
This has happened: 
https://github.com/Chicago/lead-etl/
https://github.com/Chicago/lead-model/
