### ISSUE TITLE
Modify Code to talk to new instance

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/lead-public#5]
@geneorama

**Comment by geneorama** [comment]
I'm not 100% sure what this means, but I think this refers to connecting to the postgres server.  

This has been accomplished, and the configuration is in the file `default_profile` (which is not committed publicly)

**Comment by tomschenkjr** [comment]
This is to connect to the _new_ Postgres instance with the encrypted drives. @hoatrieu has the new connection string.

**Comment by geneorama** [comment]
I put the new server address into `lead/default_profile` today, I thought it was already in there.

I'm waiting to test because according to Eric "I would hold off on running drake right now because we made some small fixes and they're not all merged."

**Comment by geneorama** [comment]
So far this seems to be working, @Hoatrieu do you want to terminate the previous instance of postgres?

**Comment by Hoatrieu** [comment]
I locked the access from analytics servers to the postgres database server

**Comment by geneorama** [comment]
Thanks @Hoatrieu, looks like transfer to the new DB is complete. Closing issue.
