### ISSUE TITLE
 Sync fork to original repo

### ISSUE THREAD

**Issue by RaedMan** [Chicago/lead-public#7]
@jtwalsh0 @geneorama  This fork doesn't seem to have been synched with the upstream repository.

**Comment by geneorama** [comment]
Ok, it's been updated.  For my future reference I only needed to use two commands: 
```
git pull https://github.com/dssg/lead-public.git master
git push origin master
 ```
The original article I used also has details about branches https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by geneorama** [comment]
Also (for my future reference) I'm using the repository on the git server `/home/geneleynes/github/lead-public` because I was worried about problems with  the `./aux` directory on Windows, which I think caused problems when I tried syncing last time.
