### ISSUE TITLE
Analytics server software requirements

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/lead-public#8]
Hi, @jtwalsh0  could you let us know what we need to install to get lead running?  We already know that we need  a Postgres client and DeDupe.  What else?

**Comment by jtwalsh0** [comment]
You also need

- [drake](https://github.com/Factual/drake)
- [mdbtools](https://github.com/brianb/mdbtools)
- ogr2ogr and shp2pgsql

**Comment by PriyaDoIT** [comment]
reopening this issue and will close once Unisys installs.

**Comment by PriyaDoIT** [comment]
Opened a 4Data Ticket #47619008

**Comment by geneorama** [comment]
I think the requirements are finally met, closing
